import streamlit as st
import google.generativeai as genai

# ----------------------------
# Gemini Setup
# ----------------------------

genai.configure(api_key="YOUR_API_KEY_HERE")

model = genai.GenerativeModel("gemini-2.5-flash")

# ----------------------------
# Page Config
# ----------------------------

st.set_page_config(
    page_title="AI Interview Coach",
    page_icon="🎯",
    layout="centered"
)

# ----------------------------
# Title
# ----------------------------

st.title("🎯 AI Interview Coach")

st.write(
    "Practice interview questions generated by AI and improve your interview skills."
)

# ----------------------------
# Sidebar
# ----------------------------

st.sidebar.header("Interview Settings")

domain = st.sidebar.selectbox(
    "Select Domain",
    [
        "HR",
        "Python",
        "DSA",
        "Operating Systems",
        "DBMS",
        "AI/ML"
    ]
)

difficulty = st.sidebar.selectbox(
    "Select Difficulty",
    [
        "Easy",
        "Medium",
        "Hard"
    ]
)

# ----------------------------
# Generate AI Question
# ----------------------------

if st.button("🎲 Generate AI Question"):

    with st.spinner("Generating question..."):

        prompt = f"""
        Generate ONE {difficulty} level interview question.

        Domain: {domain}

        Rules:
        - Return only the question.
        - Do not provide the answer.
        - Make it realistic for interviews.
        """

        response = model.generate_content(prompt)

        st.session_state.question = response.text

# ----------------------------
# Show Question
# ----------------------------

if "question" in st.session_state:

    st.subheader("📝 AI Generated Question")

    st.info(st.session_state.question)

    answer = st.text_area(
        "Enter Your Answer",
        height=200
    )

    # ----------------------------
    # Evaluate Answer
    # ----------------------------

    if st.button("📊 Evaluate Answer"):

        word_count = len(answer.split())

        if word_count >= 100:
            total_score = 18
        elif word_count >= 70:
            total_score = 15
        elif word_count >= 40:
            total_score = 12
        else:
            total_score = 8

        st.markdown("---")

        st.subheader("📊 Interview Report")

        st.write(f"Words Written: {word_count}")
        st.write(f"Total Score: {total_score}/20")

        if total_score >= 18:
            st.success("🏆 Excellent")
        elif total_score >= 15:
            st.success("👍 Good")
        elif total_score >= 10:
            st.warning("⚡ Average")
        else:
            st.error("📚 Needs Improvement")

        st.markdown("### 💡 Suggestions")

        if total_score >= 18:
            st.write(
                "Excellent answer. Add examples and real-world scenarios."
            )

        elif total_score >= 15:
            st.write(
                "Good answer. Include more technical details."
            )

        elif total_score >= 10:
            st.write(
                "Expand your answer and cover more concepts."
            )

        else:
            st.write(
                "Your answer is too short. Try explaining in more detail."
            )